# In-cluster live migration of running VM instances. Layer with kubevirt.io:view.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-vm-migration-role
  labels:
    rbac.open-cluster-management.io/filter: vm-clusterroles
    clusterview.open-cluster-management.io/discoverable: "true"
    rbac.open-cluster-management.io/custom-role: "true"
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstances
      - virtualmachineinstancemigrations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
