apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      open-cluster-management.io/policy-set: acm-hardening

generators:
  - ./policyGenerator.yaml
