apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-acs-sensors
placementBindingDefaults:
  name: binding-policy-sensor-clusters
policyDefaults:
  categories:
    - SI System and Information Integrity
  controls: 
    - SI-5 Security Alerts Advisories and Directives
  namespace: policies
  policySets:
    - acs-sensors-hub-info
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
policies:
- name: policy-acs-sync-resources
  consolidateManifests: false
  dependencies:
    - name: policy-acs-central-status
  manifests:
    - path: input-sensor/policy-acs-sync-resources.yaml
- name: policy-acs-monitor-certs
  dependencies:
    - name: policy-acs-sync-resources
  manifests:
    - path: input-sensor/acs-check-certificates.yaml
- name: policy-advanced-managed-cluster-security
  consolidateManifests: false
  manifests:
    - path: input-sensor/policy-advanced-managed-cluster-security.yaml
  policySets:
    - acs-sensor-clusters
- name: policy-advanced-managed-cluster-status
  manifests:
    - path: input-sensor/policy-advanced-managed-cluster-status.yaml
  policySets:
    - acs-sensor-clusters
  remediationAction: inform
policySets:
  - description: The Advanced Cluster Security components to setup the hub for securing
      each managed cluster.
    name: acs-sensors-hub-info
    placement:
      placementPath: placement/hub-placement.yaml
  - description: The Advanced Cluster Security components distributed to all OpenShift
      managed clusters to secure the clusters.
    name: acs-sensor-clusters
    placement:
      placementPath: placement/clusters-placement.yaml
