apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      open-cluster-management.io/policy-set: openshift-plus-setup

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous

generators:
  - ./policyGenerator.yaml
